### ISSUE TITLE
TypeError: wabt.parseWat is not a function

### ISSUE THREAD

**Issue by Astavie** [lys-lang/lys#64]
I'm getting the above error when I try to compile any .lys file.

![image](https://user-images.githubusercontent.com/7745457/89026087-52d40280-d328-11ea-8057-da8198712978.png)

**Comment by menduz** [comment]
On it https://github.com/lys-lang/lys/pull/65

**Comment by menduz** [comment]
Done, new version published. Thank you for reporting <3
